config/routes.rb
Rails.application.routes.draw do

  root 'payments/index'
  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new #untuk menampilkan form data baru
    @teacher = Teacher.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    teacher = Teacher.new (resources_params)
    teacher.save 
    redirect_to teachers_path
    flash[:notice] = 'teacher has been created'
  end   
  def edit #menampilkan data yang sudah disimpan
    @teacher = Teacher.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
  @teacher = Teacher.find(params[:id])
  @teacher.update(resources_params)
  flash[:notice] = 'teacher has been update'
  redirect_to teacher_path(@teacher)
  end    
  def destroy #untuk menghapus data
    @teacher = Teacher.find(params[:id])
    @teacher.destroy
    flash[:notice] = 'teacher has been destroy'
    redirect_to teachers_path(@teacher)
  end  
  def index #menampilkan seluruh data yang ada di database
    @teachers = Teacher.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @teacher = Teacher.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private    
  def resources_params
    params.required(:teacher).permit(:NIK, :name, :age, :kelas, :mapel)
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<%= form_for(@teacher) do |f| %>

    <%= f.label :NIK %> </br> 

    <%= f.text_field :NIK %> </br> 

    <%= f.label :name %> </br> 

    <%= f.text_field :name%> </br> 

    <%= f.label :age %> </br> 

    <%= f.text_field :age%> </br>

    <%= f.label :kelas %> </br> 

    <%= f.text_field :kelas %> </br>

    <%= f.label :mapel %> </br> 

    <%= f.text_field :mapel %> </br>

    
    <%= f.submit "Save" %> 

    <%= link_to 'Back', teachers_path %> 

<% end %>

app/views/teachers/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>NIK</th>

        <th>Name</th>

        <th>Age</th>

        <th>Kelas</th>

        <th>Mapel</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @teachers.each do |teacher| %>

    <tr>

        <td><%= teacher.NIK %></td>

        <td><%= teacher.name %></td>

        <td><%= teacher.age %></td>

        <td><%= teacher.kelas %></td>

        <td><%= teacher.mapel %></td>

        <td>
        <%= link_to 'Detail', teacher_path(teacher),  class:"btn btn-outline-info" %> 
         <%= link_to 'Edit', edit_teacher_path(teacher),  class:"btn btn-outline-secondary" %> 
          <%= link_to 'Delete', teacher_path(teacher) , method: :delete, data: {confirm: 'Apakah anda yakin?'},  class:"btn btn-outline-danger" %>
          </td>

        

    </tr>

    <% end %>

    </tbody>

</table> 
<%= link_to 'New Teacher', new_teacher_path(), class:"btn btn-outline-primary" %>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/teachers/new.html.erb
<%= form_for(@teacher) do |s| %>

    <%= s.label :NIK %> </br> 

    <%= s.text_field :NIK %> </br> 

    <%= s.label :name %> </br> 

    <%= s.text_field :name %> </br> 

    <%= s.label :age %> </br> 

    <%= s.text_field :age %> </br>

    <%= s.label :kelas %> </br> 

    <%= s.text_field :kelas %> </br>

    <%= s.label :mapel %> </br> 

    <%= s.text_field :mapel %> </br>


    <%= s.submit "Save" %> 

    <%= link_to 'Back', teachers_path %> 

    

<% end %>

app/views/teachers/show.html.erb
 <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
   
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

NIK : <%= @teacher.NIK %> </br>

Name : <%= @teacher.name %> </br>

Age : <%= @teacher.age %> </br>

Kelas : <%= @teacher.kelas %> </br>

Mapel : <%= @teacher.mapel %> </br>
  
    </div>

  </div></br>
  <%= link_to 'Back', students_path, class:"btn btn-danger"%>
  </div>
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>