config/routes.rb
Rails.application.routes.draw do

  root 'payments/index'
  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new #untuk menampilkan form data baru
    @payment = Payment.new
  end    
  def create #untuk memperoses data baru yang dimasukkan di form new
    payment = Payment.new (resources_params)
    payment.save 
    redirect_to payments_path
    flash[:notice] = 'payment has been created'
  end   
  def edit #menampilkan data yang sudah disimpan
    @payment = Payment.find(params[:id])
  end  
  def update #melakukan proses ketika user mengedit data
  @payment = Payment.find(params[:id])
  @payment.update(resources_params)
  flash[:notice] = 'payment has been update'
  redirect_to payment_path(@payment)
  end    
  def destroy #untuk menghapus data
    @payment = Payment.find(params[:id])
    @payment.destroy
    flash[:notice] = 'payment has been destroy'
    redirect_to payments_path(@payment)
  end  
  def index #menampilkan seluruh data yang ada di database
    @payments = Payment.all
  end    
  def show #menampilkan  sebuah data sectemplateara detail
    id = params[:id]
    @payment = Payment.find(id)
    # render plain: id
    # render plain: @book.title 
   end
  private    
  def resources_params
    params.required(:payment).permit(:id_transaksi, :status, :upload )
  end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/edit.html.erb
<%= form_for(@payment) do |f| %>

    <%= f.label :id_transaksi %> </br> 

    <%= f.text_field :id_transaksi %> </br> 

    <%= f.label :status %> </br> 

    <%= f.text_field :status %> </br> 

    <%= f.label :upload %> </br> 

    <%= f.text_field :upload %> </br>

    <%= f.submit "Save", class:"btn btn-outline-primary" %> 

    <%= link_to 'Back', payments_path, class:"btn btn-outline-danger" %> 

<% end %>

app/views/payments/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Id_Transaksi</th>

        <th>Status</th>

        <th>Upload</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @payments.each do |payment| %>

    <tr>

        <td><%= payment.id_transaksi %></td>

        <td><%= payment.status %></td>

        <td><%= payment.upload %></td>

        <td>
        <%= link_to 'Detail', payment_path(payment), class:"btn btn-outline-info" %> 
         <%= link_to 'Edit', edit_payment_path(payment), class:"btn btn-outline-secondary" %> 
          <%= link_to 'Delete', payment_path(payment) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
          </td>

    </tr>

    <% end %>

    </tbody>
</table> 
<%= link_to 'New payment', new_payment_path(), class:"btn btn-outline-primary" %>
</div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>
  </body>
</html>

app/views/payments/new.html.erb
<%= form_for(@payment) do |s| %>

    <%= s.label :id_transaksi %> </br> 

    <%= s.text_field :id_transaksi %> </br> 

    <%= s.label :status %> </br> 

    <%= s.text_field :status %> </br> 

    <%= s.label :upload %> </br> 

    <%= s.text_field :upload %> </br>

    <%= s.submit "Save", class:"btn btn-outline-info"%> 

    <%= link_to 'Back', payments_path(), class:"btn btn-outline-danger"%> 

<% end %>

app/views/payments/show.html.erb
 <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
    
    <% if flash[:notice].present? %>

    <%= flash[:notice] %>

    <% end %> </br>

    Id_transaksi : <%= @payment.id_transaksi %> </br>

    Status : <%= @payment.status %> </br>

    Upload : <%= @payment.upload %> </br>

    </div>

  </div></br>
  <%= link_to 'Back', payments_path, class:"btn btn-danger"%>
  </div>
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>