config/routes.rb
Rails.application.routes.draw do

  root 'payments/index'
  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
    def new #untuk menampilkan form data baru
      @exam = Exam.new
    end    
    def create #untuk memperoses data baru yang dimasukkan di form new
      exam = Exam.new (resources_params)
      exam.save 
      redirect_to exams_path
      flash[:notice] = 'exam has been created'
    end   
    def edit #menampilkan data yang sudah disimpan
      @exam = Exam.find(params[:id])
    end  
    def update #melakukan proses ketika user mengedit data
    @exam = Exam.find(params[:id])
    @exam.update(resources_params)
    flash[:notice] = 'exam has been update'
    redirect_to exam_path(@exam)
    end    
    def destroy #untuk menghapus data
      @exam = Exam.find(params[:id])
      @exam.destroy
      flash[:notice] = 'exam has been destroy'
      redirect_to exams_path(@exam)
    end  
    def index #menampilkan seluruh data yang ada di database
      @exams = Exam.all
    end    
    def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @exam = Exam.find(id)
      # render plain: id
      # render plain: @book.title 
     end
    private    
    def resources_params
      params.required(:exam).permit(:title, :mapel, :duration, :nilai, :aktifnonaktif, :level, :student_id)
    end
  end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/edit.html.erb
<%= form_for(@exam) do |f| %>

    <%= f.label :title %> </br> 

    <%= f.text_field :title %> </br> 

    <%= f.label :mapel %> </br> 

    <%= f.text_field :mapel %> </br> 

    <%= f.label :duration %> </br> 

    <%= f.text_field :duration %> </br>

    <%= f.label :nilai %> </br> 

    <%= f.text_field :nilai %> </br>

    <%= f.label :aktifnonaktif %> </br> 

    <%= f.text_field :aktifnonaktif %> </br>

     <%= f.label :level %> </br> 

    <%= f.text_field :level %> </br>

     <%= f.label :student_id %> </br> 

    <%= f.text_field :student_id %> </br>

    <%= f.submit "Save" %> 

    <%= link_to 'Back', exams_path %> 

    

<% end %>

app/views/exams/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>
        <th>Title</th>

        <th>Mapel</th>

        <th>Duration</th>

        <th>Nilai</th>

        <th>AktifNonaktif</th>

        <th>Level</th>

        <th>student_id</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @exams.each do |exam| %>

    <tr>

        <td><%= exam.title %></td>

        <td><%= exam.mapel %></td>

        <td><%= exam.duration %></td>

        <td><%= exam.nilai %></td>

        <td><%= exam.aktifnonaktif %></td>

        <td><%= exam.level %></td>

        <td><%= exam.student_id %></td>

        <td><%= link_to 'Detail', exam_path(exam), class:"btn btn-outline-info"%> 
         <%= link_to 'Edit', edit_exam_path(exam), class:"btn btn-outline-secondary" %> 
         <%= link_to 'Delete', exam_path(exam) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
        </td>
    </tr>
        <% end %>
    
        </tbody>
    
       
    </table> 
    <%= link_to 'New Exam', new_exam_path(), class:"btn btn-outline-primary" %>
    </div>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/exams/new.html.erb
<%= form_for(@exam) do |s| %>

    <%= s.label :title %> </br> 

    <%= s.text_field :title %> </br> 

    <%= s.label :mapel %> </br> 

    <%= s.text_field :mapel %> </br> 

    <%= s.label :duration %> </br> 

    <%= s.text_field :duration %> </br>

    <%= s.label :nilai %> </br> 

    <%= s.text_field :nilai %> </br>

    <%= s.label :aktifnonaktif %> </br> 

    <%= s.text_field :aktifnonaktif %> </br>

    <%= s.label :level %> </br> 

    <%= s.text_field :level %> </br>

    <%= s.label :student_id %> </br> 

    <%= s.text_field :student_id %> </br>

    <%= s.submit "Save" %> 

    <%= link_to 'Back', exams_path %> 

    

<% end %>

app/views/exams/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>

Name : <%= @exam.title %> </br>

Username : <%= @exam.mapel %> </br>

Age : <%= @exam.duration %> </br>

Kelas : <%= @exam.nilai %> </br>

Address : <%= @exam.aktifnonaktif %> </br>

City : <%= @exam.level %> </br>

NIK : <%= @exam.student_id %> </br>
    </div>

  </div></br>
  <%= link_to 'Back', exams_path, class:"btn btn-danger"%>
  </div>
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>