config/routes.rb
Rails.application.routes.draw do

  root 'payments/index'
  resources :students
  resources :teachers
  resources :exams
  resources :reports
  resources :pockets
  resources :payments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/report.rb
class Report < ApplicationRecord
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
    def new #untuk menampilkan form data baru
      @report = Report.new
    end    
    def create #untuk memperoses data baru yang dimasukkan di form new
      report = Report.new (resources_params)
      report.save 
      redirect_to reports_path
      flash[:notice] = 'report has been created'
    end   
    def edit #menampilkan data yang sudah disimpan
      @report = Report.find(params[:id])
    end  
    def update #melakukan proses ketika user mengedit data
    @report = Report.find(params[:id])
    @report.update(resources_params)
    flash[:notice] = 'report has been update'
    redirect_to report_path(@report)
    end    
    def destroy #untuk menghapus data
      @report = Report.find(params[:id])
      @report.destroy
      flash[:notice] = 'report has been destroy'
      redirect_to reports_path(@report)
    end  
    def index #menampilkan seluruh data yang ada di database
      @reports = Report.all
    end    
    def show #menampilkan  sebuah data sectemplateara detail
      id = params[:id]
      @report = Report.find(id)
      # render plain: id
      # render plain: @book.title 
     end
    private    
    def resources_params
      params.required(:report).permit(:title, :hasil, :mapel, :teacher_id, :student_id, :date)
    end
  end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/edit.html.erb
<%= form_for(@report) do |f| %>

    <%= f.label :title %> </br> 

    <%= f.text_field :title %> </br> 

    <%= f.label :hasil %> </br> 

    <%= f.text_field :hasil %> </br> 

    <%= f.label :mapel %> </br> 

    <%= f.text_field :mapel %> </br>

    <%= f.label :teacher_id %> </br> 

    <%= f.text_field :teacher_id %> </br>

    <%= f.label :student_id %> </br> 

    <%= f.text_field :student_id %> </br>

     <%= f.label :date %> </br> 

    <%= f.text_field :date %> </br>

    <%= f.submit "Save" %> 

    <%= link_to 'Back', reports_path %> 

<% end %>

app/views/reports/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<% if flash[:notice].present? %>

<%= flash[:notice] %>

<% end %> </br>
<div class="container">
<table class="table table-striped">

    <thead class="thead-dark">

    <tr>

        <th>Title</th>

        <th>Hasil</th>

        <th>Mapel</th>

        <th>Teacher_id</th>

        <th>Student_id</th>

        <th>Date</th>

        <th>Action</th>

    </tr>

    </thead>

    <tbody>

    <% @reports.each do |report| %>

    <tr>

        <td><%= report.title %></td>

        <td><%= report.hasil %></td>

        <td><%= report.mapel %></td>

        <td><%= report.teacher_id %></td>

        <td><%= report.student_id %></td>

        <td><%= report.date %></td>

        <td>
        <%= link_to 'Detail', report_path(report), class:"btn btn-outline-info" %> 
         <%= link_to 'Edit', edit_report_path(report), class:"btn btn-outline-secondary" %> 
          <%= link_to 'Delete', report_path(report) , method: :delete, data: {confirm: 'Apakah anda yakin?'}, class:"btn btn-outline-danger" %>
          </td>

        

    </tr>

    <% end %>

    </tbody>
</table> 
<%= link_to 'New report', new_report_path(), class:"btn btn-outline-primary" %>
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/reports/new.html.erb
<%= form_for(@report) do |s| %>

    <%= s.label :title %> </br> 

    <%= s.text_field :title %> </br> 

    <%= s.label :hasil %> </br> 

    <%= s.text_field :hasil %> </br> 

    <%= s.label :mapel %> </br> 

    <%= s.text_field :mapel %> </br>

    <%= s.label :teacher_id %> </br> 

    <%= s.text_field :teacher_id %> </br>

    <%= s.label :student_id %> </br> 

    <%= s.text_field :student_id %> </br>

    <%= s.label :date %> </br> 

    <%= s.text_field :date %> </br>

    <%= s.submit "Save" %> 

    <%= link_to 'Back', students_path %> 

<% end %>

app/views/reports/show.html.erb
 <!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <div class="container">
    <div class="card" style="width: 18rem;">
    <div class="card-body">
    
    <% if flash[:notice].present? %>

    <%= flash[:notice] %>

    <% end %> </br>

    Title : <%= @report.title %> </br>

    Hasil : <%= @report.hasil %> </br>

    Mapel : <%= @report.mapel %> </br>

    Teacher_id : <%= @report.teacher_id %> </br>

    Student_id : <%= @report.student_id %> </br>

    Date : <%= @report.date %> </br>

    </div>

  </div></br>
  <%= link_to 'Back', reports_path, class:"btn btn-danger"%>
  </div>
   
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>